# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd9d181b19a214e1e43d68a4c90d3670551b7d734f7d6800ae4d405aa665ed1b4efbb97d239529d1b979b16806582f34f1ee03626b22ee76e2102d402d210b4b

test:
  secret_key_base: ec5b5316da0a5ce22a23fb84d4c06358f01e4acfcd35c6b4cbda9f0b182e0efdac1a5ba6f5a0078e4447acd3086da24117232b1243ad8f0dddbe2951bed8c4d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
